FROM ghcr.io/mlflow/mlflow:v2.14.0

RUN apt-get update && apt-get install -y --no-install-recommends curl && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir psycopg2-binary
